// Generated by https?://quicktype.io

export interface IOrder {
    type?: string;
    orderNumber?: string;
    partNumber?: string;
    partName?: string;
    shipDate?: string;
    shipTime?: string;
    quantity?: number;
    quantityRack?: number;
    shipTo?: string;
    asnNumber?: string;
    orderCode?: string;
    shopCode?: string;
    fitLocation?: string;
    ecs?: string;
    pickupRoute?: string;
    kanban?: string;
    lineDeliveryCycle?: string;
    whLocationCode?: string;
    snp?: string;
    id?: number;
    status?: boolean;
    createdAt?: string;
    updatedAt?: null;
}
